name: Build Dime Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Setup Gradle wrapper
      run: |
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          ./gradlew wrapper --gradle-version=8.0
        fi
      
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace --no-daemon
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: dime-app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
